apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  # admin
  MONGO_ROOT_USERNAME: "YWRtaW4K"
  # supersecretpassword
  MONGO_ROOT_PASSWORD: "c3VwZXJzZWNyZXRwYXNzd29yZAo="
