apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karsajobs-app
  template:
    metadata:
      labels:
        app: karsajobs-app
    spec:
      containers:
        - name: karsajobs
          image: ghcr.io/untillnesss/karsajobs:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 200m
            requests:
              cpu: 100m
          ports:
            - containerPort: 8080
          env:
            - name: APP_PORT
              value: "8080"
            - name: MONGO_HOST
              value: mongo-service
            - name: MONGO_USER
              value: admin
            - name: MONGO_PASS
              value: supersecretpassword
